### ISSUE TITLE
How to use image filters in fabric 2.0?

### ISSUE THREAD

**Issue by timurmamedov** [kangax/fabric.js#4627]
Basically what the title says guys...

But, more specifically, I want to use the new Gamma filter, which is a new feature in v2.0. Problem is running command `obj.applyFilters` leads to a `TypeError: filters.filter is not a function` error. 

I have also tried downloading the latest stable build of fabric and manually adding Gamma class myself, but that didn't work either. 

Any tips or suggestions on how to use filters in v2.0 or enabling new image filtering classes in v1.7.22 are very welcome.

Cheers 🍻

## Code Used

Below is the code snippet I used to update filter values in v1.7.22 with a new slider value. It doesn't work in v2.0.

```javascript

// Get New Saturation Value
img.filters[0].saturation = parseInt(newSliderValue, 10);

// Update filter. This code throws an error.
// I presume this code is not supported anymore, if so, how would you update the filter? 
img.applyFilters(canvas.renderAll.bind(canvas));
```

**Comment by asturur** [comment]
Please add the code you tried, or move the question to stackoverflow and post the link here.

**Comment by timurmamedov** [comment]
Thanks @asturur  just updated the code 👍🏼

**Comment by asturur** [comment]
As you can read around here: http://fabricjs.com/changelog

The image applyFilter does not take a callback anymore.

img.applyFIlters();
canvas.requestRenderAll();

is your best bet.

If you want to update to 2.0 please read that link as much as you can

**Comment by timurmamedov** [comment]
Hey @asturur, thanks for clarifying that for me. I have looked at the changelog link you provided, realised you just need to pass new filter values directly.

For anyone experiencing this problem, solution is trivial:
`this.loadedImage.applyFilters([ new fabric.Image.filters.Contrast({ contrast: newSliderValue })]);`

**Comment by asturur** [comment]
You still use the filter array in the image.
image.fitlters = [ ... filtersYouNeed ]
then image.applyFilters();


is not worth creating a new filterInstance every time you need to change something.
Is wasted cpu time.

The old way of updating a filter is still valid, you just need to remove the callback from the first argument
