### ISSUE TITLE
fabric.window not initialized when running in nodejs

### ISSUE THREAD

**Issue by kdekooter** [kangax/fabric.js#4414]
## Version
1.7.19

## Steps to reproduce
Sample code in http://fabricjs.com/fabric-intro-part-4#node

## Expected Behavior
No exceptions

## Actual Behavior
`TypeError: Cannot use 'in' operator to search for 'ontouchstart' in undefined`

```
fabric.isTouchSupported = 'ontouchstart' in fabric.window;
                                         ^

TypeError: Cannot use 'in' operator to search for 'ontouchstart' in undefined
    at Object.<anonymous> (/.../node_modules/fabric/dist/fabric.js:34:42)
```

**Comment by asturur** [comment]
what version of jsdom do you have installed?

**Comment by kdekooter** [comment]
9.12.0

**Comment by asturur** [comment]
fabric 1.7 works on jsdom 3.x yet.
are you on 1.7 or latest 2.0 beta?

**Comment by kdekooter** [comment]
I am using 1.7.19. That version does not work with the latest jsdom (11.3.0): `TypeError: require(...).jsdom is not a function`

**Comment by asturur** [comment]
1.7.19 requires jsodm 3.x the old one.
that may be the cause of the error.

**Comment by kdekooter** [comment]
Ah right. Unfortunately I installation of that version fails on node 8.8 because of a node-gyp rebuild
of contextify.

**Comment by asturur** [comment]
switch to fabric 2.0
Fabric and node have still problems. Latest jsdom code, 9.12 offers transparency with node cavas but unfortunately something is not working and i have no idea how to fix it.

**Comment by kdekooter** [comment]
OK. Going for the latest and greatest then!

**Comment by asturur** [comment]
Please report any problem you find with using node. I would like to solve them asap.
